### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by servusdei2018** [TeamDei/tandem#2]
Running the app and trying to define certain words causes
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x827d0fb]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xa4ae280)
	/go/src/github.com/rivo/tview/application.go:243 +0x63
panic(0x82c6200, 0x8510a78)
	/usr/local/go/src/runtime/panic.go:513 +0x16d
main.GenAPI(0xa41a22f, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/TeamDei/tandem/api.go:70 +0x8b
main.main.func1(0x0, 0x6)
	/go/src/github.com/TeamDei/tandem/main.go:64 +0x9a
github.com/rivo/tview.(*Table).InputHandler.func1(0xa5d03e0, 0xa5e40b8)
	/go/src/github.com/rivo/tview/table.go:1240 +0x327
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xa5d03e0, 0xa5e40b8)
	/go/src/github.com/rivo/tview/box.go:163 +0x41
github.com/rivo/tview.(*Pages).InputHandler.func1(0xa5d03e0, 0xa5e40b8)
	/go/src/github.com/rivo/tview/pages.go:310 +0xa0
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xa5d03e0, 0xa5e40b8)
	/go/src/github.com/rivo/tview/box.go:163 +0x41
github.com/rivo/tview.(*Application).Run(0xa4ae280, 0x0, 0x0)
	/go/src/github.com/rivo/tview/application.go:330 +0x355
main.main()
	/go/src/github.com/TeamDei/tandem/main.go:110 +0x941

```

**Comment by servusdei2018** [comment]
Fix attempted, suspects `defer` before error handling in `api.go`, line 70.

**Comment by servusdei2018** [comment]
Fixed
