### ISSUE TITLE
net/url: invalid control character in URL

### ISSUE THREAD

**Issue by servusdei2018** [TeamDei/tandem#3]
Attempting to define a word on the end-of-line includes a `\n`, which causes
```
panic: parse http://www.perseus.tufts.edu/hopper/xmlmorph?lang=la&lookup=apiwewe
: net/url: invalid control character in URL [recovered]
	panic: parse http://www.perseus.tufts.edu/hopper/xmlmorph?lang=la&lookup=apiwewe
: net/url: invalid control character in URL

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xa4ae280)
	/go/src/github.com/rivo/tview/application.go:243 +0x63
panic(0x82d2da0, 0xa411b20)
	/usr/local/go/src/runtime/panic.go:513 +0x16d
main.main.func1(0x0, 0x6)
	/go/src/github.com/TeamDei/tandem/main.go:66 +0x4eb
github.com/rivo/tview.(*Table).InputHandler.func1(0xa411ae0, 0xa40ea20)
	/go/src/github.com/rivo/tview/table.go:1240 +0x327
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xa411ae0, 0xa40ea20)
	/go/src/github.com/rivo/tview/box.go:163 +0x41
github.com/rivo/tview.(*Pages).InputHandler.func1(0xa411ae0, 0xa40ea20)
	/go/src/github.com/rivo/tview/pages.go:310 +0xa0
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xa411ae0, 0xa40ea20)
	/go/src/github.com/rivo/tview/box.go:163 +0x41
github.com/rivo/tview.(*Application).Run(0xa4ae280, 0x0, 0x0)
	/go/src/github.com/rivo/tview/application.go:330 +0x355
main.main()
	/go/src/github.com/TeamDei/tandem/main.go:110 +0x941
```

**Comment by servusdei2018** [comment]
Fixed
